#SETUP

#LIBRARIES
library(SuperSpreadingEpidemicsMCMC)
library(coda)
library(mvtnorm)
library(MASS)
library(plotrix)
library(purrr)
library(RChronoModel)
library(stringr)
library(extraDistr)

#remove.packages("")

#FOLDERS
OUTER_FOLDER = "~/PhD_Warwick/Project_Epidemic_Modelling/Results/models/"

#BASELINE
OUTER_FOLDER = paste0(OUTER_FOLDER, 'BASELINE_DATA/DATA_BASELINE_1.5/')

OUTER_FOLDER = paste0(OUTER_FOLDER, 'BASELINE_DATA/')
OUTER_FOLDER = paste0(OUTER_FOLDER, 'BASELINE_DATA/DATA_BASELINE_1/')
OUTER_FOLDER = paste0(OUTER_FOLDER, 'BASELINE_DATA/DATA_BASELINE_1.5/')
OUTER_FOLDER = paste0(OUTER_FOLDER, 'BASELINE_DATA/MISSING/')

#SSE
OUTER_FOLDER = paste0(OUTER_FOLDER, 'SSE_DATA/DATA_SSE_1_3_1/')
OUTER_FOLDER = paste0(OUTER_FOLDER, 'SSNB_DATA/DATA_SSNB_1.6_2/')


#SSI
OUTER_FOLDER = paste0(OUTER_FOLDER, 'SSI_DATA/SSI_DATA_1/')

OUTER_FOLDER = paste0(OUTER_FOLDER, 'SSIR_DATA/')
OUTER_FOLDER = paste0(OUTER_FOLDER, 'SSIB_DATA/DATA_SSIB_2/')
OUTER_FOLDER = paste0(OUTER_FOLDER, 'SSIB_DATA/DATA_SSIB_2/')
OUTER_FOLDER = paste0(OUTER_FOLDER, 'SSIB_DATA/DATA_SSIB_4/')

#SSEB
OUTER_FOLDER = paste0(OUTER_FOLDER, 'SSEB_DATA/')

#MOCK DATA
OUTER_FOLDER = paste0(OUTER_FOLDER, 'MOCK_DATA/')
OUTER_FOLDER = paste0(OUTER_FOLDER, 'MOCK_DATA/MOCK_DATA_2_DAYS/')
OUTER_FOLDER = paste0(OUTER_FOLDER, 'MOCK_DATA/MOCK_DATA_3_DAYS/')
OUTER_FOLDER = paste0(OUTER_FOLDER, 'MOCK_DATA/MOCK_DATA_4_DAYS/')
OUTER_FOLDER = paste0(OUTER_FOLDER, 'MOCK_DATA/MOCK_DATA_6_DAYS/')
OUTER_FOLDER = paste0(OUTER_FOLDER, 'MOCK_DATA/MOCK_DATA_10_DAYS/')

